Repository Mintbase/mintbase-js, pull requests merged in 2024-08, with the labels that each got.

#530 fix(wallet): Encode nonces as base64 on redirect
  packages/wallet/src/bitte-wallet.ts
  packages/wallet/src/mintbase-wallet.ts
Labels: bug fix, Review effort [1-5]: 2

#532 Update Wallet Selector and NearAPI
  package-lock.json
  package.json
  packages/auth/package.json
  packages/data/package.json
  packages/react/package.json
  packages/react/src/MintbaseWalletContext.test.tsx
  packages/sdk/package.json
  packages/sdk/src/execute/execute.test.ts
  packages/sdk/src/execute/execute.utils.ts
  packages/sdk/src/types.ts
  packages/storage/package.json
  packages/testing/package.json
  packages/wallet/package.json
Labels: enhancement, dependencies, Review effort [1-5]: 2

#533 update packages to 0.6.2
  package-lock.json
  packages/auth/package.json
  packages/data/package.json
  packages/react/package.json
  packages/storage/package.json
  packages/testing/package.json
Labels: dependencies
